export const GET_POPULAR_PLANTS_SUCCESS = "GET_POPULAR_PLANTS_SUCCESS";
export const GET_POPULAR_PLANTS_REQUEST = "GET_POPULAR_PLANTS_REQUEST";
export const GET_POPULAR_PLANTS_FAILURE = "GET_POPULAR_PLANTS_FAILURE";
