export const GET_WISHLIST_PLANTS_REQUEST = "GET_WISHLIST_PLANTS_REQUEST";

export const GET_WISHLIST_PLANTS_SUCCESS = "GET_WISHLIST_PLANTS_SUCCESS";

export const SET_WISHLIST_PLANTS_REQUEST = "SET_WISHLIST_PLANTS_REQUEST";

export const SET_WISHLIST_PLANTS_SUCCESS = "SET_WISHLIST_PLANTS_SUCCESS";